# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SEUConnect.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(257, 200)
        MainWindow.setMinimumSize(QtCore.QSize(257, 200))
        MainWindow.setMaximumSize(QtCore.QSize(257, 200))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("inc/favicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter_5 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_5.setOrientation(QtCore.Qt.Vertical)
        self.splitter_5.setObjectName("splitter_5")
        self.splitter_4 = QtWidgets.QSplitter(self.splitter_5)
        self.splitter_4.setOrientation(QtCore.Qt.Vertical)
        self.splitter_4.setObjectName("splitter_4")
        self.splitter_3 = QtWidgets.QSplitter(self.splitter_4)
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.splitter_2 = QtWidgets.QSplitter(self.splitter_3)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.splitter = QtWidgets.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.comboBox = QtWidgets.QComboBox(self.splitter)
        self.comboBox.setEditable(False)
        self.comboBox.setCurrentText("")
        self.comboBox.setMaxVisibleItems(5)
        self.comboBox.setObjectName("comboBox")
        self.Button_refresh = QtWidgets.QPushButton(self.splitter)
        self.Button_refresh.setEnabled(True)
        self.Button_refresh.setMaximumSize(QtCore.QSize(20, 20))
        self.Button_refresh.setAutoFillBackground(False)
        self.Button_refresh.setStyleSheet("background-image:url(:/new/icon/inc/RefreshWifi.png);\n"
"border-width: 0px;\n"
"border-radius:10px;")
        self.Button_refresh.setText("")
        self.Button_refresh.setObjectName("Button_refresh")
        self.layoutWidget = QtWidgets.QWidget(self.splitter_2)
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.usrlineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.usrlineEdit.setObjectName("usrlineEdit")
        self.verticalLayout_2.addWidget(self.usrlineEdit)
        self.pwdlineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.pwdlineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pwdlineEdit.setObjectName("pwdlineEdit")
        self.verticalLayout_2.addWidget(self.pwdlineEdit)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.connect_btn = QtWidgets.QPushButton(self.splitter_3)
        self.connect_btn.setObjectName("connect_btn")
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter_4)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_3.addWidget(self.pushButton_3)
        self.save_usr_btn = QtWidgets.QPushButton(self.layoutWidget1)
        self.save_usr_btn.setObjectName("save_usr_btn")
        self.horizontalLayout_3.addWidget(self.save_usr_btn)
        self.clear_usr_btn = QtWidgets.QPushButton(self.layoutWidget1)
        self.clear_usr_btn.setObjectName("clear_usr_btn")
        self.horizontalLayout_3.addWidget(self.clear_usr_btn)
        self.label_3 = QtWidgets.QLabel(self.splitter_5)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_3.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.splitter_5, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SEUConnect"))
        self.label.setText(_translate("MainWindow", "账号："))
        self.label_2.setText(_translate("MainWindow", "密码："))
        self.connect_btn.setText(_translate("MainWindow", "自动联网"))
        self.pushButton_3.setText(_translate("MainWindow", "断开连接"))
        self.save_usr_btn.setText(_translate("MainWindow", "保存账号"))
        self.clear_usr_btn.setText(_translate("MainWindow", "清除账号"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; color:#000000;\">By:</span><a href=\"https://phower.me/\"><span style=\" font-size:10pt; text-decoration: underline; color:#000000;\">Phower</span></a></p></body></html>"))

import src_rc
